### ISSUE TITLE
Chip Voltage limits?

### ISSUE THREAD

**Issue by lock-3** [rdugan/iceriver-oc#39]
Hi,

first of all thanks for your great work!

I have 2 questions regarding the Chip Voltages of a KS0 Pro which might be of general interest. Perhaps the answers are worth mentioning in the Readme.md ?

1. What is the safe range for the Chip Voltages? I heard somewhere, that the Chips could theoretically handle a max of 500mV. The same person mentioned, that he personally would not push his Chips above 440mV to have some headroom. Is there a general guideline to safe voltages? Out of fear, this 440mV as max Chip Voltage is the bottleneck for my overclocks for now. Temps for the Chips (39°C) and Power Stage (55°C) are still fine as i have a room with pretty cold air. 

2. How exactly does the Firmware handle ramp ups after starting/restarting the miner. As far as i can tell, it would be wise to first ramp up the clock speed and then, with a little delay, ramp up the chip voltages. In this way temporary but potentially dangerous peaks for the voltage could be avoided.

For now, i simply avoid restarts to prevent any damage on my machine. If i have to restart the Miner, I do the ramp up process kind of manually which is quite time consuming. That's why i appreciate any reasonably informed answer. :)

**Comment by rdugan** [comment]
I do not provide ranges in the documentation, because there are no published specs on the chips.  Anybody suggesting they know anything about them is making stuff up (unless they work for IceRvier).

Ramping voltage is not feasible.  There is no reliable relationship between clocks and voltages across all machines.  Ramping clocks without the appropriate voltage (which i can't know) would cause many machines to crash.
