### ISSUE TITLE
Machine is offline

### ISSUE THREAD

**Issue by zmcochran** [rdugan/iceriver-oc#46]
after updating the FW and rebooting the miner does not show up in the user interface, it says its offline. I can see the miner running in the iceriver monitor tool though. Miner is a KS3M.

**Comment by rdugan** [comment]
make sure you have your network set up properly, as described in the 'Known Issues' section of the readme.  if that doesn't help, try a hardware reset (press button for 30s) and then reload the firmware.

**Comment by ZycoMonk** [comment]
i have also an issue with "machine down" now on my KS0 pro.. i think everything worked fine, till i decided to move the miner to a different land connected it therefore with via dlan.
if i try to connect to my miner now, the site opens, but after logging in it says "the machine is offline".
if i check the pool the miner seems to be running, as i can see that the miner is doing his 200 GH/s
oh forgotten to say - the miner is running the stock firmware - i can't upload the PBFarmer Firmware in this situation

any idea why this happened? do i have to reset everything?
will i be able to set it all back up then? because if i cannot connect after the reset, the miner won't mine for me anymore

**Comment by ZycoMonk** [comment]
oh damn... i ressetet my miner, to update it with the latest PBFarmer firmware, and now it still isn't availible...
still shows after log in "machine is offline" :,-(

**Comment by ZycoMonk** [comment]
hmmm... changed the lan cable - still "machine is offline"
did again a reset --> miner was online
so i installed the oc firmware... hope it will stay online now, so that i can make changes to the miner :-/
