### ISSUE TITLE
sedra/kaspa split mining? 

### ISSUE THREAD

**Issue by SomethingGettingWrong** [rdugan/iceriver-oc#52]
Could you in theory add a sedra/kaspa rotation for example where it can split mine the hashrate either at the same time or possibly  a set time period say 12 hours of sedra then 12 hours of kaspa daily?

**Comment by rdugan** [comment]
I have another firmware package intended for commercial installations or hosting facilities, that has a traffic splitting feature.  This can be used to run multiple coins in parallel.  But it has a slightly higher fee at 1.33% instead of 1%.

It hasn't been released yet, so if you want to use it, find me in the Kaspa discord (pbfarmer)
