### ISSUE TITLE
pool switching

### ISSUE THREAD

**Issue by chad5150** [rdugan/iceriver-oc#8]
2 things
1- switch to a different pool and shows connected but doesnt hash and shares - reboot does not fix.
2 - switch to a different pool and does not connect regardless of pool and show 0 difficulty etc. - reboot does not fix
To fix either you have to restore factory - reflash - change away from your pool to get connected to a pool again. What made me notice this is the yellow circles by  the oc setting that says oc's have disabled since cannot reconnect.
also to fully get the interface back to "stock" you need to go and delete the bg folder under var/temp through netbeeans and reset with the button the machine. 
2 edits deep here - i finally had to go back to the v4 to restore pool fuctionality

**Comment by rdugan** [comment]
Upon further discussion this appears to simply be the unavailability of herominers.  Added a little more description of expected behavior in the README.

Additionally, there is never a need to manually modify files on the machine to return to stock, especially in /var/tmp, as that directory is automatically wiped on even a normal reboot.
