### ISSUE TITLE
New firmwares bricking devices!! (KS2, KS1 tested)

### ISSUE THREAD

**Issue by MrKTOTO** [rdugan/iceriver-oc#93]
several devices have already frozen during operation, it writes an error that the device is not available, rebooting does not help, after resetting to factory settings on version 0.8 and higher, the equipment interface completely stops loading, resetting by the reset button does not help. However, those devices that were on version 0.7.1, resetting by the button helped. As a result, I already have 4 bricked devices due to the new firmware, everything I tried to restore does not help.

**Comment by MrKTOTO** [comment]
You cannot use versions 0.8 and higher, this will brick your device.

**Comment by rdugan** [comment]
They're not bricked.  You need to read the README.

https://github.com/rdugan/iceriver-oc#known-issues

**Comment by MrKTOTO** [comment]
what specific item? It's definitely not the browser cache, I tried to access them from several devices and several browsers.

**Comment by rdugan** [comment]
It was almost certainly a cache/refresh problem before you reset, now it sounds like the last item. The only changes from 0.7 to 0.8 were replacing the web app (including migrating to https).  The mining side was unchanged, and factory reset has always been stock IR code.

Otherwise it's almost certainly your network setup - also all discussed in that section.

**Comment by MrKTOTO** [comment]
Okay, well, how do you then explain that the devices don't work in three differently configured networks?

**Comment by rdugan** [comment]
Everything i can explain / tell you is in the docs I linked.  I don't have any further info I can provide.

Have you opened the app by typing the IP explicitly (no copy/paste) in a private/incognito window, as documented?

If that doesn't work, then do what the second item suggests.

**Comment by MrKTOTO** [comment]
yes, I read the instructions before I started resetting to factory settings, what docs say doesn't help

**Comment by rdugan** [comment]
not before resetting.  after.

read the last item.  it's referring to what happens AFTER you reset.

**Comment by MrKTOTO** [comment]
![Screenshot_20241117_153651_AnyDesk](https://github.com/user-attachments/assets/47541beb-3609-48d4-93ca-ffd1627d3c5c)

See, it's in incognito mode

**Comment by MrKTOTO** [comment]
Device bricked, your instructions not working!

**Comment by MrKTOTO** [comment]
this does not happen on versions below 0.8, only on 0.8 and above

**Comment by MrKTOTO** [comment]
![Screenshot_20241117_153651_AnyDesk](https://github.com/user-attachments/assets/a739003f-0b57-4a47-b0e4-04434aa52933)
Another computer

**Comment by MrKTOTO** [comment]
![20241117_154143](https://github.com/user-attachments/assets/96504238-8270-4b2e-a250-7580d757cb58)

**Comment by MrKTOTO** [comment]
![Screenshot_20241117_154332_Samsung Internet](https://github.com/user-attachments/assets/6b31096f-6fc6-48f1-a876-48c444b7593f)
From phone

**Comment by MrKTOTO** [comment]
browser cache from all devices? do you take me for an idiot?

**Comment by chad5150** [comment]
Did you reset the device through the web interface or on the physical device. I’ve reset my devices through the web interface and had weird issues both on stock firmware and this firmware.

**Comment by rdugan** [comment]
> browser cache from all devices? do you take me for an idiot?

1. Being an ass isn't going to convince me to help you - especially with a problem with your stock firmware
2. Neither issue i've told you to focus on were cache - one is a browser bug reverting from https to http (and yes, it happens on all browsers you've used to view the https site), and the other is network configuration.  If you simply confirmed you've taken the steps I keep asking you about, this would move much more quickly.
3. Clearly your device is not 'bricked' as you keep saying, considering there is a web server running and answering requests.

Now, if you'd like my help, please answer the questions below:

1. Have you performed a hardware reset by holding the button down for at least 30 seconds?  Have you tried doing this a few times?
2. what happens when you type http://192.168.0.95/user/login
